### ISSUE TITLE
System.Text.Encodings.Web Exception

### ISSUE THREAD

**Issue by godrage** [DuendeArchive/IdentityModel.OidcClient#199]
with the versions in the screenshot (identitymodel 4.0.0 and oidcclient 3.0.0) it works,
but as soon as I upgrade to 4.1.1 and 4.0.0p2 I get those exceptions.

```
Exception-Message: 
The type initializer for 'System.Text.Encodings.Web.DefaultUrlEncoder' threw an exception.; 

Exception-Trace: 
   at IdentityModel.Internal.QueryHelpers.AddQueryString(String uri, IEnumerable`1 queryString)
   at IdentityModel.OidcClient.AuthorizeClient.CreateAuthorizeUrl(String state, String nonce, String codeChallenge, IDictionary`2 extraParameters)
   at IdentityModel.OidcClient.AuthorizeClient.CreateAuthorizeState(IDictionary`2 extraParameters)
   at IdentityModel.OidcClient.AuthorizeClient.<AuthorizeAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityModel.OidcClient.OidcClient.<LoginAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CORES_UI.Auth.CORESClient.<LoginAsync>d__34.MoveNext(); 

InnerException-Message: 
The type initializer for 'PerTypeValues`1' threw an exception.; 
```

![refs](https://user-images.githubusercontent.com/14147748/76170518-e131c700-6182-11ea-9ebd-4ed58fef0a4b.PNG)

using:
-oidcclient
-odata client
-newtsonsoft.json
-system.componentmodel.annotations (for odata models)

.. slightly desperate - I am sorry for the issue, but any hints/help is highly appreciated.

**Comment by leastprivilege** [comment]
@blowdart any idea?

**Comment by blowdart** [comment]
That shouldn't throw ever. Version mismatch somehow? What version of .NET? Can you post your project or packages.json please?

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.

**Comment by afetouh** [comment]
I have the same error. Does anyone have a solution for it?.
Your help is highly appreciated

**Comment by antmx** [comment]
I fixed this problem by adding an assembly reference to my project for this assembly:
System.Runtime.CompilerServices.Unsafe.dll
Various versions are available on Nuget. I actually already had the Nuget package "installed" according to Nuget Package Manager, but I still had to add the assembly reference too. In my case assembly v4.0.4.1 from Nuget package v4.5.3 did the trick.
