### ISSUE TITLE
ProcessResponseAsync needs NewtonSoft.Json.dll v10.0.0.0

### ISSUE THREAD

**Issue by gjvdkamp** [DuendeArchive/IdentityModel.OidcClient#210]
Hi, 

I'm trying to use manual flow b/c the webbrowser threading issues are making my head hurt. 

When I feed data, state to ProcessResponseAsync I get an error result with this error: 
```
Error validating token response: Error validating identity token: System.ArgumentException: IDX12729: Unable to decode the header '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]' as Base64Url encoded string. jwtEncodedString: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'. ---> System.TypeInitializationException: The type initializer for 'System.IdentityModel.Tokens.Jwt.JsonExtensions' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at System.IdentityModel.Tokens.Jwt.JsonExtensions..cctor()
   --- End of inner exception stack trace ---
   at System.IdentityModel.Tokens.Jwt.JsonExtensions.DeserializeJwtHeader(String jsonString)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityToken.Decode(String[] tokenParts, String rawData)
   --- End of inner exception stack trace ---
   at System.IdentityModel.Tokens.Jwt.JwtSecurityToken.Decode(String[] tokenParts, String rawData)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ReadJwtToken(String token)
   at IdentityModel.OidcClient.IdentityTokenValidator.<ValidateAsync>d__4.MoveNext()
```

Which seems to come from this internal error: 
`System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. `

I can't seem to figure out how to redirect underlying libraries, but I am also puzzled how OIDCClient comes with 11.0.2.xx when it is looking for 10.0.0.?

**Comment by gjvdkamp** [comment]
I also tried the Automatic flow, same response.

**Comment by gjvdkamp** [comment]
I did have to change the Start Url maunally to get it to go down the right flow, I couldn''t figure out how to do that through the options (I need a form post back). 

Woudl that have anythig

**Comment by gjvdkamp** [comment]
This is something outside of OIDCClient
