### ISSUE TITLE
Error loading discovery document: Error connecting to http://165.88.125.xxx:9600/.well-known/openid-configuration. Operation is not valid due to the current state of the object..

### ISSUE THREAD

**Issue by ChangYinHan** [DuendeArchive/IdentityModel.OidcClient#322]
Hi，

An exception occurs when I try to call login through COM component.

exception message: Error loading discovery document: Error connecting to http://165.88.125.128:9600/.well-known/openid-configuration. Operation is not valid due to the current state of the object..
  ```
One or more errors occurred.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Pki.Matchar.SecurityLogin.SecurityClient.SecurityClient.Login()
   at Pki.Matchar.SecurityLogin.COM.Implementation.SecurityManager.Login(String AppID) in C:\github.com\PerkinElmer\Matchar-Mergemodules\Pki.Matchar.SecurityLogin\Pki.Matchar.SecurityLogin.COM\Implementation\SecurityManager.cs:line 98
mscorlib
inner exception
Error loading discovery document: Error connecting to http://165.88.125.128:9600/.well-known/openid-configuration. Operation is not valid due to the current state of the object..
   at IdentityModel.OidcClient.OidcClient.<EnsureProviderInformationAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityModel.OidcClient.OidcClient.<EnsureConfigurationAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityModel.OidcClient.OidcClient.<LoginAsync>d__9.MoveNext()
IdentityModel.OidcClient
inner exception
Operation is not valid due to the current state of the object.
   at System.Text.Json.JsonElement.EnumerateObject()
   at IdentityModel.Client.DiscoveryDocumentResponse.ValidateEndpoints(JsonElement json, DiscoveryPolicy policy)
   at IdentityModel.Client.DiscoveryDocumentResponse.Validate(DiscoveryPolicy policy)
   at IdentityModel.Client.DiscoveryDocumentResponse.InitializeAsync(Object initializationData)
   at IdentityModel.Client.ProtocolResponse.<FromHttpResponseAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at IdentityModel.Client.HttpClientDiscoveryExtensions.<GetDiscoveryDocumentAsync>d__1.MoveNext()
System.Text.Json
```

And my options is:
![image](https://user-images.githubusercontent.com/75602404/124080034-76458700-da7c-11eb-80c7-da3ebb87d057.png)

Does anyone can help me? thanks a lot.

**Comment by leastprivilege** [comment]
closing. no answers.
